### ISSUE TITLE
Backward routing throwing 404 error 

### ISSUE THREAD

**Issue by Shelly011s** [Superposition-Chennai/Coding-Chrysanthemums#6]
## Problem Description:
When an external link is reached and we want to go back to the previous page instead of showing the list of useful links it throws 404 error.
![Screenshot from 2021-11-10 00-22-15](https://user-images.githubusercontent.com/84381373/140986770-ee28dc75-167a-41c4-8b2d-ef51566127e3.png)

**Comment by rakshaa2000** [comment]
Issue with Hash Routing, Resolved 👍
